# Using Pandas

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [2]:
## Your Code here
import pandas as pd
import numpy as np
pd.set_option("display.max.rows", 200)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
y = pd.read_csv("vehicles.csv")
x = pd.DataFrame(y)

In [3]:
x[(x["Make"].str.contains("Dutton"))]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,"E. P. Dutton, Inc.",Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,S and S Coach Company E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Superior Coaches Div E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

In [4]:
x["Make"] = x["Make"].replace(["E. P. Dutton, Inc.", "S and S Coach Company  E.p. Dutton", "Superior Coaches Div E.p. Dutton"], "Dutton")

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [5]:
## Your Code here
#35952
x[(x["Make"].str.contains("Dutton"))]
x

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,Dutton,Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

Note:
<br>Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Converting Gallons to Liters

1 Gallon = 3.78541 Liters

In [6]:
## Your Code here
x.loc[:, "Transmission type"] = 0

In [7]:
x[x.columns[x.columns.str.contains("MPG")]] = x[x.columns[x.columns.str.contains("MPG")]] / 3.78541 / 1.60934 
x

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Transmission type
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,2.954689,2.790540,2.790540,522.764706,1950,0
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.133942,2.133942,2.133942,683.615385,2550,0
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,2.626390,2.790540,2.626390,555.437500,2100,0
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.133942,2.133942,2.133942,683.615385,2550,0
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,2.298091,3.447137,2.626390,555.437500,2550,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,244.000000,1100,0
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,243.000000,1100,0
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,244.000000,1100,0
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.401826,5.909378,246.000000,1100,0
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,5.252780,6.401826,5.745229,255.000000,1150,0

In [8]:
x["CO2 Emission Grams/Mile"] = x["CO2 Emission Grams/Mile"] * 1.60934

In [9]:
x["transmission_type"]=x.Transmission.apply(lambda x: 1 if x.startswith("Auto") else 0)
x

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Transmission type,transmission_type
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,2.954689,2.790540,2.790540,841.306152,1950,0,1
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.133942,2.133942,2.133942,1100.169583,2550,0,1
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,2.626390,2.790540,2.626390,893.887786,2100,0,1
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.133942,2.133942,2.133942,1100.169583,2550,0,1
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,2.298091,3.447137,2.626390,893.887786,2550,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,392.678960,1100,0,1
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,391.069620,1100,0,1
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,392.678960,1100,0,1
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.401826,5.909378,395.897640,1100,0,1
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,5.252780,6.401826,5.745229,410.381700,1150,0,0

In [10]:
x.Transmission.apply(lambda x: 1 if x.startswith("Auto") else 0)

0        1
1        1
2        1
3        1
4        1
        ..
35947    1
35948    1
35949    1
35950    1
35951    0
Name: Transmission, Length: 35952, dtype: int64

In [11]:
x

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Transmission type,transmission_type
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,2.954689,2.790540,2.790540,841.306152,1950,0,1
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.133942,2.133942,2.133942,1100.169583,2550,0,1
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,2.626390,2.790540,2.626390,893.887786,2100,0,1
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.133942,2.133942,2.133942,1100.169583,2550,0,1
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,2.298091,3.447137,2.626390,893.887786,2550,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,392.678960,1100,0,1
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,391.069620,1100,0,1
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.237677,5.909378,392.678960,1100,0,1
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,5.581079,6.401826,5.909378,395.897640,1100,0,1
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,5.252780,6.401826,5.745229,410.381700,1150,0,0

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [12]:
# Your Code here
car_counter = {}
list(x["Make"].unique())

['AM General',
 'ASC Incorporated',
 'Acura',
 'Alfa Romeo',
 'American Motors Corporation',
 'Aston Martin',
 'Audi',
 'Aurora Cars Ltd',
 'Autokraft Limited',
 'BMW',
 'BMW Alpina',
 'Bentley',
 'Bertone',
 'Bill Dovell Motor Car Company',
 'Bitter Gmbh and Co. Kg',
 'Bugatti',
 'Buick',
 'CCC Engineering',
 'CX Automotive',
 'Cadillac',
 'Chevrolet',
 'Chrysler',
 'Consulier Industries Inc',
 'Dabryan Coach Builders Inc',
 'Dacia',
 'Daewoo',
 'Daihatsu',
 'Dodge',
 'Dutton',
 'Eagle',
 'Environmental Rsch and Devp Corp',
 'Evans Automobiles',
 'Excalibur Autos',
 'Federal Coach',
 'Ferrari',
 'Fiat',
 'Fisker',
 'Ford',
 'GMC',
 'General Motors',
 'Genesis',
 'Geo',
 'Goldacre',
 'Grumman Allied Industries',
 'Grumman Olson',
 'Honda',
 'Hummer',
 'Hyundai',
 'Import Foreign Auto Sales Inc',
 'Import Trade Services',
 'Infiniti',
 'Isis Imports Ltd',
 'Isuzu',
 'J.K. Motors',
 'JBA Motorcars, Inc.',
 'Jaguar',
 'Jeep',
 'Kia',
 'Laforza Automobile Inc',
 'Lambda Control Systems',
 'Lamborghini',
 'Land Rover',
 'Lexus',
 'Lincoln',
 'London Coach Co Inc',
 'London Taxi',
 'Lotus',
 'MINI',
 'Mahindra',
 'Maserati',
 'Maybach',
 'Mazda',
 'McLaren Automotive',
 'Mcevoy Motors',
 'Mercedes-Benz',
 'Mercury',
 'Merkur',
 'Mitsubishi',
 'Mobility Ventures LLC',
 'Morgan',
 'Nissan',
 'Oldsmobile',
 'PAS Inc - GMC',
 'PAS, Inc',
 'Pagani',
 'Panos',
 'Panoz Auto-Development',
 'Panther Car Company Limited',
 'Peugeot',
 'Pininfarina',
 'Plymouth',
 'Pontiac',
 'Porsche',
 'Quantum Technologies',
 'Qvale',
 'Ram',
 'Red Shift Ltd.',
 'Renault',
 'Rolls-Royce',
 'Roush Performance',
 'Ruf Automobile Gmbh',
 'SRT',
 'Saab',
 'Saleen',
 'Saleen Performance',
 'Saturn',
 'Scion',
 'Shelby',
 'Spyker',
 'Sterling',
 'Subaru',
 'Suzuki',
 'TVR Engineering Ltd',
 'Tecstar, LP',
 'Texas Coach Company',
 'Toyota',
 'VPG',
 'Vector',
 'Vixen Motor Company',
 'Volga Associated Automobile',
 'Volkswagen',
 'Volvo',
 'Wallace Environmental',
 'Yugo',
 'smart']

In [13]:
x.groupby(by='Make').agg('count')

,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Transmission type,transmission_type
Make,,,,,,,,,,,,,,,,
AM General,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
ASC Incorporated,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Acura,302,302,302,302,302,302,302,302,302,302,302,302,302,302,302,302
Alfa Romeo,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41
American Motors Corporation,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
Aston Martin,133,133,133,133,133,133,133,133,133,133,133,133,133,133,133,133
Audi,890,890,890,890,890,890,890,890,890,890,890,890,890,890,890,890
Aurora Cars Ltd,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Autokraft Limited,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
BMW,1677,1677,1677,1677,1677,1677,1677,1677,1677,1677,1677,1677,1677,1677,1677,1677
BMW Alpina,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Bentley,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116
Bertone,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Bill Dovell Motor Car Company,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Bitter Gmbh and Co. Kg,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Bugatti,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Buick,537,537,537,537,537,537,537,537,537,537,537,537,537,537,537,537
CCC Engineering,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
CX Automotive,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Cadillac,508,508,508,508,508,508,508,508,508,508,508,508,508,508,508,508
Chevrolet,3643,3643,3643,3643,3643,3643,3643,3643,3643,3643,3643,3643,3643,3643,3643,3643
Chrysler,641,641,641,641,641,641,641,641,641,641,641,641,641,641,641,641
Consulier Industries Inc,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Dabryan Coach Builders Inc,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Dacia,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Daewoo,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67
Daihatsu,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Dodge,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360,2360
Dutton,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Eagle,156,156,156,156,156,156,156,156,156,156,156,156,156,156,156,156
Environmental Rsch and Devp Corp,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Evans Automobiles,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Excalibur Autos,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Federal Coach,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Ferrari,208,208,208,208,208,208,208,208,208,208,208,208,208,208,208,208
Fiat,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43
Fisker,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Ford,2946,2946,2946,2946,2946,2946,2946,2946,2946,2946,2946,2946,2946,2946,2946,2946
GMC,2347,2347,2347,2347,2347,2347,2347,2347,2347,2347,2347,2347,2347,2347,2347,2347
General Motors,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Genesis,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Geo,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144,144
Goldacre,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Grumman Allied Industries,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Grumman Olson,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Honda,836,836,836,836,836,836,836,836,836,836,836,836,836,836,836,836
Hummer,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
Hyundai,662,662,662,662,662,662,662,662,662,662,662,662,662,662,662,662
Import Foreign Auto Sales Inc,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Import Trade Services,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Infiniti,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345,345
Isis Imports Ltd,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Isuzu,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409,409
J.K. Motors,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
"JBA Motorcars, Inc.",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Jaguar,343,343,343,343,343,343,343,343,343,343,343,343,343,343,343,343
Jeep,829,829,829,829,829,829,829,829,829,829,829,829,829,829,829,829
Kia,493,493,493,493,493,493,493,493,493,493,493,493,493,493,493,493
Laforza Automobile Inc,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Lambda Control Systems,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Lamborghini,104,104,104,104,104,104,104,104,104,104,104,104,104,104,104,104
Land Rover,142,142,142,142,142,142,142,142,142,142,142,142,142,142,142,142
Lexus,397,397,397,397,397,397,397,397,397,397,397,397,397,397,397,397
Lincoln,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273,273
London Coach Co Inc,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
London Taxi,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Lotus,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53
MINI,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320,320
Mahindra,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Maserati,111,111,111,111,111,111,111,111,111,111,111,111,111,111,111,111
Maybach,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31
Mazda,915,915,915,915,915,915,915,915,915,915,915,915,915,915,915,915
McLaren Automotive,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Mcevoy Motors,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Mercedes-Benz,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284,1284
Mercury,532,532,532,532,532,532,532,532,532,532,532,532,532,532,532,532
Merkur,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Mitsubishi,950,950,950,950,950,950,950,950,950,950,950,950,950,950,950,950
Mobility Ventures LLC,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Morgan,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Nissan,1253,1253,1253,1253,1253,1253,1253,1253,1253,1253,1253,1253,1253,1253,1253,1253
Oldsmobile,376,376,376,376,376,376,376,376,376,376,376,376,376,376,376,376
PAS Inc - GMC,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
"PAS, Inc",2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Pagani,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Panos,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Panoz Auto-Development,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Panther Car Company Limited,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Peugeot,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74
Pininfarina,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Plymouth,456,456,456,456,456,456,456,456,456,456,456,456,456,456,456,456
Pontiac,784,784,784,784,784,784,784,784,784,784,784,784,784,784,784,784
Porsche,862,862,862,862,862,862,862,862,862,862,862,862,862,862,862,862
Quantum Technologies,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Qvale,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Ram,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57
Red Shift Ltd.,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Renault,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33
Rolls-Royce,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160,160
Roush Performance,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53
Ruf Automobile Gmbh,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
SRT,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Saab,410,410,410,410,410,410,410,410,410,410,410,410,410,410,410,410
Saleen,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Saleen Performance,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Saturn,278,278,278,278,278,278,278,278,278,278,278,278,278,278,278,278
Scion,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83
Shelby,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Spyker,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Sterling,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Subaru,781,781,781,781,781,781,781,781,781,781,781,781,781,781,781,781
Suzuki,512,512,512,512,512,512,512,512,512,512,512,512,512,512,512,512
TVR Engineering Ltd,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
"Tecstar, LP",6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Texas Coach Company,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Toyota,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836,1836
VPG,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Vector,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Vixen Motor Company,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Volga Associated Automobile,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Volkswagen,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047
Volvo,717,717,717,717,717,717,717,717,717,717,717,717,717,717,717,717
Wallace Environmental,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
Yugo,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
smart,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20

In [14]:
x.value_counts("Transmission")

Transmission
Automatic 4-spd                     10585
Manual 5-spd                         7787
Automatic (S6)                       2631
Automatic 3-spd                      2597
Manual 6-spd                         2423
Automatic 5-spd                      2171
Automatic 6-spd                      1432
Manual 4-spd                         1306
Automatic (S8)                        960
Automatic (S5)                        822
Automatic (variable gear ratios)      675
Automatic 7-spd                       662
Automatic (S7)                        261
Auto(AM-S7)                           256
Automatic 8-spd                       243
Automatic (S4)                        229
Auto(AM7)                             157
Auto(AV-S6)                           145
Auto(AM6)                             110
Auto(AM-S6)                            92
Automatic 9-spd                        90
Manual 3-spd                           74
Manual 7-spd                           68
Auto(AV-S7)                            63
Auto(AV-S8)                            26
Automatic (S9)                         26
Auto(AM5)                              12
Automatic (AV-S6)                       9
Auto(AM-S8)                             6
Auto(AM8)                               5
Automatic (AV)                          4
Automatic (A6)                          4
Manual(M7)                              3
Automatic (A1)                          3
Automatic (AM5)                         2
Auto(L4)                                2
Auto(L3)                                2
Auto (AV)                               2
Auto (AV-S6)                            1
Automatic 6spd                          1
Automatic (AM6)                         1
Manual 5 spd                            1
Auto(AM-S9)                             1
Auto(A1)                                1
Auto (AV-S8)                            1
dtype: int64

In [15]:
x.value_counts("Drivetrain")

Drivetrain
Front-Wheel Drive             13044
Rear-Wheel Drive              12726
4-Wheel or All-Wheel Drive     6503
All-Wheel Drive                2039
4-Wheel Drive                  1058
2-Wheel Drive                   423
Part-time 4-Wheel Drive         158
2-Wheel Drive, Front              1
dtype: int64

In [16]:
x.sort_values(by="Fuel Barrels/Year", ascending=False)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Transmission type,transmission_type
20898,Lamborghini,Countach,1990,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,0.984896,1.641494,1.149046,2043.172083,5800,0,0
20896,Lamborghini,Countach,1988,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,0.984896,1.641494,1.149046,2043.172083,5800,0,0
20895,Lamborghini,Countach,1987,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,0.984896,1.641494,1.149046,2043.172083,5800,0,0
20894,Lamborghini,Countach,1986,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,0.984896,1.641494,1.149046,2043.172083,5800,0,0
20897,Lamborghini,Countach,1989,5.2,12.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,47.087143,0.984896,1.641494,1.149046,2043.172083,5800,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17296,Honda,Civic CNG,2009,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Subcompact Cars,CNG,0.066429,3.939585,5.909378,4.596183,407.480577,1100,0,1
17396,Honda,Civic Natural Gas,2013,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,4.432033,6.237677,5.088631,350.836120,1000,0,1
17398,Honda,Civic Natural Gas,2015,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,4.432033,6.237677,5.088631,350.836120,1000,0,1
17397,Honda,Civic Natural Gas,2014,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,4.432033,6.237677,5.088631,350.836120,1000,0,1
17395,Honda,Civic Natural Gas,2012,1.8,4.0,Automatic 5-spd,Front-Wheel Drive,Compact Cars,CNG,0.060000,4.432033,6.237677,5.088631,368.046973,1000,0,1

<b> (Optional)

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [19]:
## your Code here
x.groupby("Make")["CO2 Emission Grams/Mile"].mean()

Make
AM General                           983.883276
ASC Incorporated                     893.887786
Acura                                680.083467
Alfa Romeo                           746.656697
American Motors Corporation          813.937904
Aston Martin                        1082.470692
Audi                                 725.419405
Aurora Cars Ltd                      953.480305
Autokraft Limited                    867.596969
BMW                                  736.231766
BMW Alpina                           913.751959
Bentley                             1104.082334
Bertone                              650.100208
Bill Dovell Motor Car Company        841.306152
Bitter Gmbh and Co. Kg               913.751959
Bugatti                             1405.054404
Buick                                699.200056
CCC Engineering                      953.480305
CX Automotive                        889.171583
Cadillac                             798.685042
Chevrolet                            825.075305
Chrysler                             719.002404
Consulier Industries Inc             681.057361
Dabryan Coach Builders Inc           878.697536
Dacia                                621.834982
Daewoo                               624.033649
Daihatsu                             499.198053
Dodge                                892.386794
Dutton                              1233.915689
Eagle                                661.676963
Environmental Rsch and Devp Corp     893.887786
Evans Automobiles                    752.747609
Excalibur Autos                     1021.586041
Federal Coach                        933.914214
Ferrari                             1146.874180
Fiat                                 490.312081
Fisker                               271.978460
Ford                                 829.560235
GMC                                  919.723603
General Motors                       794.566921
Genesis                              746.963666
Geo                                  542.472450
Goldacre                             794.566921
Grumman Allied Industries            841.306152
Grumman Olson                        573.468068
Honda                                575.391478
Hummer                               946.311280
Hyundai                              619.630810
Import Foreign Auto Sales Inc        752.747609
Import Trade Services                922.586187
Infiniti                             743.277435
Isis Imports Ltd                     715.110229
Isuzu                                790.535784
J.K. Motors                         1012.666891
JBA Motorcars, Inc.                  953.480305
Jaguar                               794.040089
Jeep                                 802.707699
Kia                                  628.670654
Laforza Automobile Inc              1300.200416
Lambda Control Systems               841.306152
Lamborghini                         1214.701665
Land Rover                           966.786978
Lexus                                712.865096
Lincoln                              783.656569
London Coach Co Inc                  893.887786
London Taxi                          744.685509
Lotus                                715.339705
MINI                                 504.877095
Mahindra                             819.154060
Maserati                             998.917774
Maybach                             1174.105711
Mazda                                678.051221
McLaren Automotive                   787.304259
Mcevoy Motors                        727.656022
Mercedes-Benz                        806.574090
Mercury                              703.151018
Merkur                               790.947266
Mitsubishi                           694.385320
Mobility Ventures LLC                881.113650
Morgan                               841.306152
Nissan                               734.112337
Oldsmobile                           709.262569
PAS Inc - GMC                        953.480305
PAS, Inc                            1021.586041
Pagani                              1079.867140
Panos                                953.480305
Panoz Auto-Development               650.100208
Panther Car Company Limited          706.597012
Peugeot                              755.146238
Pininfarina                          701.423909
Plymouth                             670.850768
Pontiac                              666.954267
Porsche                              746.428881
Quantum Technologies                 681.057361
Qvale                                681.057361
Ram                                  772.747188
Red Shift Ltd.                       621.834982
Renault                              579.083173
Rolls-Royce                         1231.268456
Roush Performance                   1000.872897
Ruf Automobile Gmbh                 1100.169583
SRT                                  976.869380
Saab                                 713.723440
Saleen                               960.683797
Saleen Performance                  1060.877812
Saturn                               605.619222
Scion                                533.328707
Shelby                               841.306152
Spyker                               936.222743
Sterling                             788.007029
Subaru                               650.682011
Suzuki                               632.064322
TVR Engineering Ltd                  794.566921
Tecstar, LP                         1100.169583
Texas Coach Company                 1191.850382
Toyota                               701.343618
VPG                                  919.457620
Vector                              1688.454707
Vixen Motor Company                 1023.942575
Volga Associated Automobile          752.747609
Volkswagen                           632.054961
Volvo                                701.356415
Wallace Environmental               1058.929674
Yugo                                 573.034887
smart                                397.556154
Name: CO2 Emission Grams/Mile, dtype: float64

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [28]:
## Your Code is here 

x.groupby("transmission_type")["CO2 Emission Grams/Mile"].mean()

transmission_type
0    724.463282
1    784.381775
Name: CO2 Emission Grams/Mile, dtype: float64